{% set name = "PACKAGENAME" %}
{% set version = load_setup_py_data().version %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - easyterm  >=1.0.0
    - ncbi_db 
    - gawk
    - blast
    - mafft
    - ete3 == 3.1.1
    - biopython >=1.46
    - trimal
    - brewer2mpl

entry_points:
    - alignment_tools = biotree_tools.alignment_tools:main


about:
  home: "https://github.com/marco-mariotti/{{ name }}"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Description of project"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - marco-mariotti
